# Generated by Django 5.0.5 on 2024-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usr',
        ),
        migrations.AddField(
            model_name='item',
            name='contact_info',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
